<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-IK83RTK7" name="Default test" tests="4" failures="1" timestamp="18 Aug 2021 03:31:17 GMT" time="8.766" errors="0">
  <testcase name="f" time="6.2" classname="com.qingzi.test.ApiTest_qz"/>
  <testcase name="f" time="0.724" classname="com.qingzi.test.ApiTest_qz"/>
  <testcase name="f" time="0.612" classname="com.qingzi.test.ApiTest_qz"/>
  <testcase name="f" time="0.721" classname="com.qingzi.test.ApiTest_qz">
    <failure type="java.lang.AssertionError" message="expected [200,success,title] but found [{&amp;quot;data&amp;quot;:{&amp;quot;meetingId&amp;quot;:&amp;quot;1-M-83985614847057920&amp;quot;,&amp;quot;sdkAccountId&amp;quot;:&amp;quot;101100494753569&amp;quot;,&amp;quot;sdkRoomId&amp;quot;:&amp;quot;10012047586605&amp;quot;,&amp;quot;sdkAccountToken&amp;quot;:&amp;quot;48b717e5829041beeff69079217931832dea32df188ab1f952961c6b002e364c&amp;quot;,&amp;quot;roomCode&amp;quot;:&amp;quot;79624387169570816&amp;quot;,&amp;quot;maxParticipants&amp;quot;:200,&amp;quot;maxTime&amp;quot;:36000000,&amp;quot;quality&amp;quot;:&amp;quot;Medium&amp;quot;,&amp;quot;hostAccountId&amp;quot;:&amp;quot;CN-86-1-UA-52895296005488640&amp;quot;,&amp;quot;hostSDKId&amp;quot;:&amp;quot;101100494753569&amp;quot;,&amp;quot;hostBUid&amp;quot;:&amp;quot;60ab63e725706d5a9e959e0c&amp;quot;,&amp;quot;title&amp;quot;:&amp;quot;会议-ff&amp;quot;,&amp;quot;beginTime&amp;quot;:1629257476956,&amp;quot;videoStatus&amp;quot;:0,&amp;quot;audioStatus&amp;quot;:0,&amp;quot;unMuteNeedRequest&amp;quot;:0,&amp;quot;pwd&amp;quot;:&amp;quot;237485&amp;quot;,&amp;quot;status&amp;quot;:&amp;quot;Running&amp;quot;,&amp;quot;lock&amp;quot;:0,&amp;quot;newMeeting&amp;quot;:true,&amp;quot;userAccountId&amp;quot;:&amp;quot;CN-86-1-UA-52895296005488640&amp;quot;,&amp;quot;mId&amp;quot;:&amp;quot;113856469&amp;quot;,&amp;quot;MRId&amp;quot;:&amp;quot;1-MR-79624387192389632&amp;quot;},&amp;quot;code&amp;quot;:200,&amp;quot;message&amp;quot;:&amp;quot;SUCCESS&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [200,success,title] but found [{"data":{"meetingId":"1-M-83985614847057920","sdkAccountId":"101100494753569","sdkRoomId":"10012047586605","sdkAccountToken":"48b717e5829041beeff69079217931832dea32df188ab1f952961c6b002e364c","roomCode":"79624387169570816","maxParticipants":200,"maxTime":36000000,"quality":"Medium","hostAccountId":"CN-86-1-UA-52895296005488640","hostSDKId":"101100494753569","hostBUid":"60ab63e725706d5a9e959e0c","title":"会议-ff","beginTime":1629257476956,"videoStatus":0,"audioStatus":0,"unMuteNeedRequest":0,"pwd":"237485","status":"Running","lock":0,"newMeeting":true,"userAccountId":"CN-86-1-UA-52895296005488640","mId":"113856469","MRId":"1-MR-79624387192389632"},"code":200,"message":"SUCCESS"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.qingzi.test.ApiTest_qz.f(ApiTest_qz.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Default test -->
